Remove OS_object from OS_sysmon_object.h
There seems to be a duplicate conflict:

```
/home/user/Downloads/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sysmon/OS_sysmon_object.h:20:1: error: duplicate interface definition for class 'OS_object'
@interface OS_object
^
/home/user/Downloads/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/os/object.h:203:1: note: previous definition is here
OS_OBJECT_DECL_BASE(object, NSObject);
```